### ISSUE TITLE
Add .env setting for encryption seed for user accounts (and chainAccounts token funding accounts)

### ISSUE THREAD

**Issue by traylewin** [API-market/ore-js#9]
Currently, a newly created user accounts' private key is encrypted using ORE_OWNER_ACCOUNT_ACTIVE_PRIVATE_KEY

Instead, we should create a new key pair specifically for use for encrypting user accounts
USER_ACCOUNT_ENCRYPTION_PUBLIC_KEY and  USER_ACCOUNT_ENCRYPTION_PRIVATE_KEY

Then, we should use the USER_ACCOUNT_ENCRYPTION_PUBLIC_KEY to asymmetrically encrypt the new user's private key (instead of using the USER_ACCOUNT_ENCRYPTION_PRIVATE_KEY

This will allow us to create scripts and tooling that can encrypt keys (like those stored in the oreid-staging database) without needing a private key

**Comment by peteknowsai** [comment]
Issue moved to [API-market/ore-id #639](https://github.com/API-market/ore-id/issues/639) via [**ZenHub**](https://www.zenhub.com/)
